name: Check for Disallowed Commands

on: [pull_request]

jobs:
  check-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get list of modified files
        id: files
        uses: actions/github-script@v6
        with:
          script: |
            const files = await github.paginate(
              github.rest.pulls.listFiles, 
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              }
            );
            return { result: files.map(file => file.filename).join(" ") };

      - name: Check for disallowed commands
        run: |
          # Find uncommented lines containing the disallowed commands
          disallowed_commands="display|show|head|tail|describe|print"
          files="${{ steps.files.outputs.result }}"
          if [ -n "$files" ]; then
            matches=$(grep -E -i -n "^\s*[^#]*\b($disallowed_commands)\b" $files || true)
            if [ -n "$matches" ]; then
              echo "Error: Found disallowed commands in the code:"
              echo "$matches"
              exit 1
            else
              echo "No disallowed commands found."
            fi
          else
            echo "No Python files modified."